server:
  port: 9093

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-accounts
          uri: lb://user-accounts
          predicates:
            - Path=/user-accounts/**
        - id: api-interceptor
          uri: lb://api-interceptor
          predicates:
#            - Path=/v1/bible-reader/**
            - Path=/v1/got/**
#            - Path=/v1/news/**


# Discovery Server Access
eureka:
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
