server:
  port: 8583

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-accounts
          uri: http://localhost:8075/
          predicates:
            - Path=/user-accounts/**
        - id: api-interceptor
          uri: http://localhost:8068/
          predicates:
            - Path=/api-interceptor/**


# Discovery Server Access
eureka:
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
    healthcheck:
      enabled: true